swagger: "2.0"
info:
  version: "0.0.1"
  title: EOI API Movies
host: localhost:10010
basePath: /api
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /movies/{movie_uuid}:
    x-swagger-router-controller: movies
    get:
      description: Obtenemos la película indicada
      operationId: getMovie
      parameters:
        - in: path
          name: movie_uuid
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: "#/definitions/Movie"
        default:
          description: Error
          schema:
            items:
              $ref: "#/definitions/ErrorResponse"  
    delete:
      description: Borramos una película
      operationId: deleteMovie
      parameters:
        - in: path
          name: movie_uuid
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
  /movies:
    x-swagger-router-controller: movies
    get:
      description: Obtenemos todas las películas
      operationId: getMovies
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/Movie"
        default:
          description: Error
          schema:
            type: array
            items:
              $ref: "#/definitions/ErrorResponse"
    post:
      description: Creamos una nueva película
      parameters:
        - name: movie
          in: body
          description: La película a crear
          required: true
          schema: 
            $ref: "#/definitions/Movie"
      operationId: newMovie
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Movie"
        default:
          description: Error
          schema:
            type: array
            items:
              $ref: "#/definitions/ErrorResponse"
    put:
      description: Actualizamos una película
      operationId: updateMovie
      parameters:
        - in: body
          name: movie
          description: La película a modificar
          required: true
          schema:
            $ref: "#/definitions/Movie"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Movie" 
    
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  SuccessResponse:
    required:
      - message
    properties:
      message:
        type: string
  Movie:
    required:
      - uuid
      - name
    properties:
      name:
        type: string
      uuid: 
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
